{
 "title": "Order Dashboard",
 "time": { "from": "2015-12-31T18:30:00.000Z", "to": "2016-12-31T18:29:59.000Z" },
 "panels": [
  {
   "title": "Sales By Channel",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "sales_channel.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "lines.amount", "id": "1", "type": "sum" }
     ],
     "timeField": "purchased_at"
    }
   ]
  },
  {
   "title": "Order Panel",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "status.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "purchased_at"
    }
   ]
  },
  {
   "title": "Top10 Sales",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "salesman.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "total_amount", "id": "1", "type": "sum" }
     ],
     "timeField": "purchased_at"
    }
   ]
  }
 ]
}